[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "lerobot_workspace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
config-leader = """
python lerobot/lerobot/scripts/configure_motor.py \
  --port /dev/LeRobotLeader \
  --brand feetech \
  --model sts3215 \
  --baudrate 1000000 \
  --ID """

config-follower = """
python lerobot/lerobot/scripts/configure_motor.py \
  --port /dev/LeRobotFollower \
  --brand feetech \
  --model sts3215 \
  --baudrate 1000000 \
  --ID """

calibrate-follower = """
python lerobot/lerobot/scripts/control_robot.py calibrate \
  --robot-path lerobot/lerobot/configs/robot/moss.yaml \
  --robot-overrides '~cameras' '~leader_arms' follower_arms.main.port=/dev/LeRobotFollower \
  --arms main_follower
"""

[dependencies]
python = "==3.10"
ffmpeg = "*"
opencv = ">=4.10.0"
# These dependencies to fix issues installing lerobot using pypi-dependencies
numpy = "==1.26.4" # numba from lerobot requires < 2.X
rerun-sdk = ">=0.15.1" # pixi fails to resolve rerun-sdk for lerobot

[pypi-dependencies]
lerobot = { path = "./lerobot", editable = true, extras = ["feetech"]}
